// Builds the map of Italy with every region in ONE shared coordinate system, so the regions sit next to each other
// and a single region can be lifted out of the map (used by the region celebration and the Stats map).
// Same ISTAT GeoJSON as generate-region-shapes.ts (openpolis/geojson-italy, limits_IT_regions.geojson).
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import simplify from 'simplify-js';

const NAME_MAP: Record<string, string> = {
  "Valle d'Aosta/Vallée d'Aoste": "Valle d'Aosta",
  'Trentino-Alto Adige/Südtirol': 'Trentino-Alto Adige',
};

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: tsx scripts/generate-italy-map.ts <geojson-path>');
  process.exit(1);
}

interface Feature {
  properties: { reg_name: string };
  geometry: { type: string; coordinates: number[][][][] | number[][][] };
}

const geojson = JSON.parse(readFileSync(inputPath, 'utf-8'));
const WIDTH = 300;
const TOLERANCE = 0.03;
const MIN_ISLAND_AREA = 0.03; // square degrees, so the tiny islets are left out

// One projection for the whole country: longitude shrunk by the cosine of the mean latitude of Italy
const lonScale = Math.cos((42 * Math.PI) / 180);

const ringArea = (ring: number[][]) => {
  let sum = 0;
  for (let i = 0; i < ring.length - 1; i++) sum += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
  return Math.abs(sum / 2);
};

const regions: { name: string; rings: { x: number; y: number }[][] }[] = [];
for (const feature of geojson.features as Feature[]) {
  const name = NAME_MAP[feature.properties.reg_name] ?? feature.properties.reg_name;
  const polygons = (feature.geometry.type === 'Polygon' ? [feature.geometry.coordinates] : feature.geometry.coordinates) as number[][][][];
  const outers = polygons.map(p => p[0]).sort((a, b) => ringArea(b) - ringArea(a));
  const rings = outers
    .filter((ring, i) => i === 0 || ringArea(ring) >= MIN_ISLAND_AREA)
    .map(ring => simplify(ring.map(([lon, lat]) => ({ x: lon * lonScale, y: -lat })), TOLERANCE, true))
    .filter(ring => ring.length >= 4);
  regions.push({ name, rings });
}

const all = regions.flatMap(r => r.rings.flat());
const minX = Math.min(...all.map(p => p.x));
const maxX = Math.max(...all.map(p => p.x));
const minY = Math.min(...all.map(p => p.y));
const maxY = Math.max(...all.map(p => p.y));
const scale = WIDTH / (maxX - minX);
const round = (n: number) => Math.round(n * 10) / 10;

const out: Record<string, { path: string; cx: number; cy: number; w: number; h: number }> = {};
for (const r of regions) {
  const pts = r.rings.flat().map(p => ({ x: (p.x - minX) * scale, y: (p.y - minY) * scale }));
  const rx = pts.map(p => p.x);
  const ry = pts.map(p => p.y);
  const d = r.rings
    .map(ring => 'M' + ring.map(p => `${round((p.x - minX) * scale)},${round((p.y - minY) * scale)}`).join('L') + 'Z')
    .join('');
  out[r.name] = {
    path: d,
    cx: round((Math.min(...rx) + Math.max(...rx)) / 2),
    cy: round((Math.min(...ry) + Math.max(...ry)) / 2),
    w: round(Math.max(...rx) - Math.min(...rx)),
    h: round(Math.max(...ry) - Math.min(...ry)),
  };
}

const width = round(WIDTH);
const height = round((maxY - minY) * scale);
const outputPath = path.resolve(import.meta.dirname, '../src/data/italyMap.ts');
writeFileSync(
  outputPath,
  `// Auto-generated by scripts/generate-italy-map.ts from ISTAT region boundaries.
// Every region is in the same coordinate system, inside a ${width} x ${height} box.
export interface MapRegion {
  path: string;
  /** centre and size of the bounding box of the region */
  cx: number;
  cy: number;
  w: number;
  h: number;
}

export const ITALY_MAP = { width: ${width}, height: ${height} };

export const MAP_REGIONS: Record<string, MapRegion> = ${JSON.stringify(out, null, 2)};
`,
);
console.log(`Wrote ${Object.keys(out).length} regions, ${width}x${height}, ${(JSON.stringify(out).length / 1024).toFixed(1)} KB`);
