// Converts the ISTAT region boundaries GeoJSON into simplified, pre-scaled SVG path
// data so the app can render each region's real silhouette without shipping the
// full ~71k-point dataset or a mapping library.
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import simplify from 'simplify-js';

const NAME_MAP: Record<string, string> = {
  Piemonte: 'Piemonte',
  "Valle d'Aosta/Vallée d'Aoste": "Valle d'Aosta",
  Liguria: 'Liguria',
  Lombardia: 'Lombardia',
  'Trentino-Alto Adige/Südtirol': 'Trentino-Alto Adige',
  Veneto: 'Veneto',
  'Friuli-Venezia Giulia': 'Friuli-Venezia Giulia',
  'Emilia-Romagna': 'Emilia-Romagna',
  Marche: 'Marche',
  Toscana: 'Toscana',
  Umbria: 'Umbria',
  Lazio: 'Lazio',
  Campania: 'Campania',
  Abruzzo: 'Abruzzo',
  Molise: 'Molise',
  Puglia: 'Puglia',
  Basilicata: 'Basilicata',
  Calabria: 'Calabria',
  Sicilia: 'Sicilia',
  Sardegna: 'Sardegna',
};

interface Point {
  x: number;
  y: number;
}

function ringArea(ring: number[][]): number {
  let sum = 0;
  for (let i = 0; i < ring.length - 1; i++) {
    const [x1, y1] = ring[i];
    const [x2, y2] = ring[i + 1];
    sum += x1 * y2 - x2 * y1;
  }
  return Math.abs(sum / 2);
}

function largestRing(geometry: { type: string; coordinates: unknown }): number[][] {
  const polygons = (
    geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates
  ) as number[][][][];

  let best: number[][] = [];
  let bestArea = -1;
  for (const poly of polygons) {
    const outer = poly[0];
    const area = ringArea(outer);
    if (area > bestArea) {
      bestArea = area;
      best = outer;
    }
  }
  return best;
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: tsx scripts/generate-region-shapes.ts <geojson-path>');
  process.exit(1);
}

const geojson = JSON.parse(readFileSync(inputPath, 'utf-8'));

const MAX_W = 60;
const MAX_H = 80;
const TOLERANCE = 0.045;

const result: Record<string, { path: string; width: number; height: number }> = {};

interface Feature {
  properties: { reg_name: string };
  geometry: { type: string; coordinates: unknown };
}

for (const feature of geojson.features as Feature[]) {
  const name = NAME_MAP[feature.properties.reg_name];
  if (!name) {
    console.warn('Unmapped region:', feature.properties.reg_name);
    continue;
  }

  const ring = largestRing(feature.geometry);

  // A degree of longitude is shorter than a degree of latitude away from the
  // equator, so raw lon/lat would stretch every shape horizontally. Scale
  // longitude by cos(latitude) (using this region's own mean latitude) so the
  // silhouette keeps its real-world proportions.
  const meanLatDeg = ring.reduce((sum, [, lat]) => sum + lat, 0) / ring.length;
  const lonScale = Math.cos((meanLatDeg * Math.PI) / 180);

  const points: Point[] = ring.map(([lon, lat]) => ({ x: lon * lonScale, y: -lat }));
  const simplified = simplify(points, TOLERANCE, true);

  const xs = simplified.map((p) => p.x);
  const ys = simplified.map((p) => p.y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);
  const bboxW = maxX - minX;
  const bboxH = maxY - minY;
  const scale = Math.min(MAX_W / bboxW, MAX_H / bboxH);
  const outW = Math.round(bboxW * scale * 10) / 10;
  const outH = Math.round(bboxH * scale * 10) / 10;

  const d =
    simplified
      .map((p, i) => {
        const x = Math.round((p.x - minX) * scale * 10) / 10;
        const y = Math.round((p.y - minY) * scale * 10) / 10;
        return `${i === 0 ? 'M' : 'L'}${x},${y}`;
      })
      .join(' ') + ' Z';

  result[name] = { path: d, width: outW, height: outH };
  console.log(`${name}: ${points.length} -> ${simplified.length} points, ${outW}x${outH}`);
}

const missing = Object.values(NAME_MAP).filter((n) => !result[n]);
if (missing.length) console.warn('Missing regions in output:', missing);

const outputPath = path.resolve(import.meta.dirname, '../src/data/regionShapes.ts');
const fileContent = `// Auto-generated by scripts/generate-region-shapes.ts from ISTAT region boundaries.
export interface RegionShape {
  path: string;
  width: number;
  height: number;
}

export const REGION_SHAPES: Record<string, RegionShape> = ${JSON.stringify(result, null, 2)};
`;

writeFileSync(outputPath, fileContent);
console.log(`\nWrote ${Object.keys(result).length} region shapes to ${outputPath}`);
